apiVersion: v1
kind: Service
metadata:
  name: school-api-service
  labels:
    app: school-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: school-api 